server:
  port: 9000

spring:
  application:
    name: api-gate

routes:
  - id: eureka_client1
    uri: http://localhost:9091/
    predicates:
      - Path=/service1/**
  - id: eureka_client2
    uri: http://localhost:9090/
    predicates:
      - Path=/service2/**

