server:
  port: 9000

spring:
  application:
    name: api-gate

routes:
  - id: eureka_client1
    uri: http://localhost:9091/
    predicates:
      - Path=//sum2numbers/**
  - id: eureka_client2
    uri: http://localhost:9092/
    predicates:
      - Path=/users/**

